/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SendRequest } from './sendRequest';
import { DropoffStatus } from './dropoffStatus';


/**
 * I accept and will pick it up Receiver -> Backend
 */
export interface SendResponse { 
    request: SendRequest;
    status: DropoffStatus;
    pickup_date: string;
}

