/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type ShipmentSizes = 'S' | 'M' | 'L' | 'XL';

export const ShipmentSizes = {
    S: 'S' as ShipmentSizes,
    M: 'M' as ShipmentSizes,
    L: 'L' as ShipmentSizes,
    XL: 'XL' as ShipmentSizes
};

